{% set name = "redshift_connector" %}
{% set version = "2.0.876" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/aws/amazon-redshift-python-driver/archive/v{{ version }}.tar.gz
  sha256: e8e5619a8d86123435aff1004e40870d11fda9d5158610c52147c091c9251157

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - scramp >=1.2.0,<1.3.0
    - pytz >=2020.1,<2020.2
    - beautifulsoup4 >=4.7.0,<4.8.0
    - boto3 >=1.16.8,<1.17.0
    - requests >=2.23.0,<2.24.0
    - lxml >=4.2.5,<4.6.0
    - botocore >=1.19.8,<1.20.0

test:
  imports:
    - redshift_connector

about:
  home: https://github.com/aws/amazon-redshift-python-driver/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Pure Python connector for Amazon Redshift
  description: |
    redshift_connector is the Amazon Redshift connector for Python. Easy integration with 
    pandas and numpy, as well as support for numerous Amazon Redshift specific features 
    help you get you the most out of your data.
  doc_url: https://github.com/aws/amazon-redshift-python-driver/
  dev_url: https://github.com/aws/amazon-redshift-python-driver/

extra:
  recipe-maintainers:
    - Brooke-white
