schema_version: 1

context:
  name: redshift_connector
  version: "2.1.15"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/aws/amazon-redshift-python-driver/archive/v${{ version }}.tar.gz
  sha256: 45bf54ad345a49c736d2d2e3c7ee8e68bc409b3c22ea6f474b300d31977e9539

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - wheel
    - pytest
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - scramp >=1.2.0,<1.5.0
    - pytz >=2020.1
    - beautifulsoup4 >=4.7.0,<5.0.0
    - boto3 >=1.9.201,<2.0.0
    - requests >=2.23.0,<3.0.0
    - lxml >=4.6.5,<6.0.0
    - botocore >=1.12.201,<2.0.0
    - packaging
    - setuptools

tests:
  - python:
      imports:
        - redshift_connector
      pip_check: true
      python_version: ${{ python_min }}

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Pure Python connector for Amazon Redshift
  description: |
    redshift_connector is the Amazon Redshift connector for Python. Easy integration with
    pandas and numpy, as well as support for numerous Amazon Redshift specific features
    help you get you the most out of your data.
  homepage: https://github.com/aws/amazon-redshift-python-driver/
  repository: https://github.com/aws/amazon-redshift-python-driver/
  documentation: https://github.com/aws/amazon-redshift-python-driver/

extra:
  recipe-maintainers:
    - Brooke-white
    - bsharifi
    - personal-naveenkumar
    - rxm7706
    - vahid110
